### ISSUE TITLE
IsNullOrEmpty completion in if generates bad code

### ISSUE THREAD

**Issue by csharpner** [controlflow/resharper-postfix#17]
I have a variable named exitFileRecord of a POCO type.  I write this code:

if (exitFileRecord._agentName.isnullor

I'm prompted with a popup for code completion that properly changes it to:

if (string.IsNullOrEmpty(exitFileRecord._agentName)

But when I continue and add this:

if (string.IsNullOrEmpty(exitFileRecord._agentName) && exitFileRecord._cert.issnullor

when I type that last "r", I have the pop up prompt with the suggested code change (which is correct in the popup), it changes it and ends up with this:

if (string.IsNullOrEmpty(exitFileRecord._agentName) && string.IsNullOrEmpty(String.IsNullOrEmptyd._cert))

That's not my typo on the Emptyd._cert.  If leaves out my variable entirely and puts string.IsNullOrEmpty twice like you see here, followed by "d._cert".

**Comment by iccfish** [comment]
I think I have the same issue...... And I've post it on youtrack: https://youtrack.jetbrains.com/issue/RSPL-6375?query=Subsystem%3A+PostfixCompletion

**Comment by controlflow** [comment]
YAY, finally reproduced this, looks like all you have 'Automatically insert parentheses after completion' setting turned off...

**Comment by controlflow** [comment]
Fix will be available soon in version >2.0.9, thank you all for your feedback!

**Comment by iccfish** [comment]
Thanks, just for information, I HAVE to turn 'Automatically insert parentheses after completion' due to this option will cause more major issue in code completion: https://youtrack.jetbrains.com/issue/RSRP-426530

**Comment by iccfish** [comment]
Just for a hello... I wonder if could tell me about the roadmap about new version due to this issue bothers me many times a day..

**Comment by controlflow** [comment]
Fix available in version `2.1` (in both R# 8.x and R# 9.x builds), just uploaded to resharper gallery.
