### ISSUE TITLE
Help to use generic parameters in postfix fashion

### ISSUE THREAD

**Issue by citizenmatt** [controlflow/resharper-postfix#31]
I don't know how this would work, but I always end up using a generic parameter `T` without having declared it in the method or class, and resharper's greedy code completion always adds a totally useless class name:

    public void Foo(IEnumerable<ThreadStaticAttribute>

Can postfix do something to help? Add a 'create T' item in the code completion for `IEnumerable<` above? Any better ideas?

**Comment by controlflow** [comment]
Hmm, we can introduce template-like item `T` (available where? only in signature?), that will populate type parameter declaration with hotspot placeholders on complete... that sounds like a good idea to try...

**Comment by controlflow** [comment]
Will be available in upcoming 2.2
