### ISSUE TITLE
Resharper 9.1 support

### ISSUE THREAD

**Issue by Mharlin** [controlflow/resharper-postfix#34]
Thanks for a great extension!

Now when R# 9.1 is out I was hoping for some support for it.

**Comment by mariusmg** [comment]
Yes, please.

I need .notnull  :)

**Comment by laurentkempe** [comment]
:+1:

**Comment by dampir** [comment]
Yes, please add support for R# 9.1.

**Comment by controlflow** [comment]
I always thought open-source is all about merging pull requests :(
ReSharper 9.1 RTM compatible build is waiting you in extensions gallery, grab it while it's hot!

**Comment by laurentkempe** [comment]
I forked the repo on the week end and started to adapt but you were still faster...

**Comment by controlflow** [comment]
Thanks, sorry for not mentioning that this issue was in progress.
I really hope we merge this plugin into ReSharper codebase for the next major release :)

**Comment by dampir** [comment]
Native support will be great!

**Comment by laurentkempe** [comment]
Yes I think this plugin should be part of the product!
