### ISSUE TITLE
Abadon 8.x support

### ISSUE THREAD

**Issue by controlflow** [controlflow/resharper-postfix#38]
* Time has come. Prepare plugin for bundling into R# source code;
* Rewrite to new 9.x code completion items infrastructure, introduce completion filter for postfix items;
* Use accept behavior instead of event hack in static members completion;
* Tweak presentation of static members code completion;
* Implement R# 9.x 'Code style' application where appropriate;
* Once again try making plugin language-agnostic;

**Comment by hmemcpy** [comment]
+1!

I should do this for mine as well...

**Comment by dampir** [comment]
+1!!!

**Comment by controlflow** [comment]
Code completion part is rewritten, support for 8.x and 9.0 is abadoned, postfix is now language-agnostic and ready for JS implementation. Other tasks has separate issue tickets, closing this one.
