### ISSUE TITLE
.await could add async modifier to the method

### ISSUE THREAD

**Issue by asizikov** [controlflow/resharper-postfix#41]
When I have a Task returning method like this: 

```
public Task Foo()
{
    SomethingAsync().await
}
```
The .await template produces noncompilable code. R# has a 'Make method 'Foo' async' quick fix for that, though.
Is that possible to invoke the quick fix automatically by default or at least have it as an option of choice?

**Comment by controlflow** [comment]
Hm, maybe this is good idea, thanks!

**Comment by controlflow** [comment]
Implemented in upcoming ReSahrper 10 EAPs, thanks for the idea :+1:
