### ISSUE TITLE
Not Showing up in R# 9.2

### ISSUE THREAD

**Issue by trbngr** [controlflow/resharper-postfix#53]
Fresh VS install. 

Postfix is not available in the R# Extension Manager.

I'm unable to install my favorite extension. :(

**Comment by controlflow** [comment]
Yep, it's not ready yet. I'll try to ship it in a day or two

**Comment by ltrzesniewski** [comment]
Gotta +1 on the *favorite extension* part ;-)
It's only when the extension is missing that you notice how hard you're addicted to it :-)

Thanks for this awesome stuff! :+1:

**Comment by wwwlicious** [comment]
+1 my favourite extension too. Thanks so much :)

**Comment by controlflow** [comment]
You can grab pre-release `2.2.1-beta` version of plugin in ReSharper 9.2 extension gallery (make sure "Include prerelease packages" is enabled in 'ReSharper' - 'Options' - 'Extension Manager' page). Release version will be available soon.

**Comment by trbngr** [comment]
Thanks!

**Comment by trbngr** [comment]
It's broken for me.

http://www.youtube.com/watch?v=x7YIB5Z5BKI

**Comment by controlflow** [comment]
That was the different issue, fixed in `2.2.2-beta`, just uploaded to extension gallery.
