### ISSUE TITLE
Type completion of argument is no longer performed at the time of the definition of the function in version 2.2-beta

### ISSUE THREAD

**Issue by ryo1988** [controlflow/resharper-postfix#54]
We have always used.
Thank you very much.

Type completion of argument is no longer performed at the time of the definition of the function in version 2.2-beta R#9.2

**Comment by iccfish** [comment]
Yeah....I also meet this issue, type completion in function declaration was missing if postfix installed.

**Comment by controlflow** [comment]
Sorry, folks, fixed this in `2.2.1-beta`

**Comment by ryo1988** [comment]
We made sure the fix.
Thank you very much.
