### ISSUE TITLE
Please release for ReSharper 10

### ISSUE THREAD

**Issue by workabyte** [controlflow/resharper-postfix#61]
LOVE this plug in but we just moved to VS2015 so i have to put in RS10 :(

**Comment by derigel23** [comment]
@pcKris don't worry - in version 10 postfix is embedded in ReSharper itself. :)

**Comment by workabyte** [comment]
I know, saw that right after I posted and felt like a complete newb :(

**Comment by workabyte** [comment]
@derigel23 looks like they dropped the .format :'( one of my favorite ones.
guess i will have to stop being so lazy
